# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exp.grpcServer.gRPC.python.hypernetwork_pb2 as hypernetwork__pb2


class HnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloWorld = channel.unary_unary(
                '/Hn.Hn/HelloWorld',
                request_serializer=hypernetwork__pb2.HelloMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.HelloMsg.FromString,
                )
        self.GetHs = channel.unary_unary(
                '/Hn.Hn/GetHs',
                request_serializer=hypernetwork__pb2.VertexMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.HsMsg.FromString,
                )
        self.AddHs = channel.unary_unary(
                '/Hn.Hn/AddHs',
                request_serializer=hypernetwork__pb2.HsMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.VertexMsg.FromString,
                )
        self.DeleteHs = channel.unary_unary(
                '/Hn.Hn/DeleteHs',
                request_serializer=hypernetwork__pb2.HsMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.VertexMsg.FromString,
                )
        self.GetHn = channel.unary_unary(
                '/Hn.Hn/GetHn',
                request_serializer=hypernetwork__pb2.EmptyMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.HsMsg.FromString,
                )
        self.CreateHnByString = channel.unary_unary(
                '/Hn.Hn/CreateHnByString',
                request_serializer=hypernetwork__pb2.HnByStringMsg.SerializeToString,
                response_deserializer=hypernetwork__pb2.HnMsg.FromString,
                )


class HnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloWorld(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddHs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateHnByString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloWorld': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloWorld,
                    request_deserializer=hypernetwork__pb2.HelloMsg.FromString,
                    response_serializer=hypernetwork__pb2.HelloMsg.SerializeToString,
            ),
            'GetHs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHs,
                    request_deserializer=hypernetwork__pb2.VertexMsg.FromString,
                    response_serializer=hypernetwork__pb2.HsMsg.SerializeToString,
            ),
            'AddHs': grpc.unary_unary_rpc_method_handler(
                    servicer.AddHs,
                    request_deserializer=hypernetwork__pb2.HsMsg.FromString,
                    response_serializer=hypernetwork__pb2.VertexMsg.SerializeToString,
            ),
            'DeleteHs': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHs,
                    request_deserializer=hypernetwork__pb2.HsMsg.FromString,
                    response_serializer=hypernetwork__pb2.VertexMsg.SerializeToString,
            ),
            'GetHn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHn,
                    request_deserializer=hypernetwork__pb2.EmptyMsg.FromString,
                    response_serializer=hypernetwork__pb2.HsMsg.SerializeToString,
            ),
            'CreateHnByString': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHnByString,
                    request_deserializer=hypernetwork__pb2.HnByStringMsg.FromString,
                    response_serializer=hypernetwork__pb2.HnMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Hn.Hn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloWorld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/HelloWorld',
            hypernetwork__pb2.HelloMsg.SerializeToString,
            hypernetwork__pb2.HelloMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/GetHs',
            hypernetwork__pb2.VertexMsg.SerializeToString,
            hypernetwork__pb2.HsMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddHs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/AddHs',
            hypernetwork__pb2.HsMsg.SerializeToString,
            hypernetwork__pb2.VertexMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteHs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/DeleteHs',
            hypernetwork__pb2.HsMsg.SerializeToString,
            hypernetwork__pb2.VertexMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/GetHn',
            hypernetwork__pb2.EmptyMsg.SerializeToString,
            hypernetwork__pb2.HsMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateHnByString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hn.Hn/CreateHnByString',
            hypernetwork__pb2.HnByStringMsg.SerializeToString,
            hypernetwork__pb2.HnMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
