# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hypernetwork.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hypernetwork.proto',
  package='Hn',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12hypernetwork.proto\x12\x02Hn\"\x19\n\x08HelloMsg\x12\r\n\x05hello\x18\x01 \x01(\t\"\x1b\n\tVertexMsg\x12\x0e\n\x06vertex\x18\x01 \x01(\t\"\xbe\x01\n\x05HsMsg\x12\x0e\n\x06vertex\x18\x01 \x01(\t\x12\x0f\n\x07simplex\x18\x02 \x03(\t\x12\x0e\n\x06partOf\x18\x03 \x03(\t\x12 \n\x06hsType\x18\x04 \x01(\x0e\x32\x10.Hn.HsMsg.HsType\x12\t\n\x01R\x18\x05 \x01(\t\x12\t\n\x01t\x18\x06 \x01(\x05\x12\t\n\x01M\x18\x07 \x03(\t\x12\t\n\x01N\x18\x08 \x01(\t\x12\x0b\n\x03psi\x18\t \x01(\t\")\n\x06HsType\x12\n\n\x06VERTEX\x10\x00\x12\t\n\x05\x41LPHA\x10\x01\x12\x08\n\x04\x42\x45TA\x10\x02\"(\n\x0b\x44\x65leteHsMsg\x12\x0e\n\x06vertex\x18\x01 \x01(\t\x12\t\n\x01R\x18\x02 \x01(\t\"j\n\x05HnMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\x02Hn\x18\x02 \x03(\x0b\x32\x11.Hn.HnMsg.HnEntry\x1a\x34\n\x07HnEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.Hn.HsMsg:\x02\x38\x01\")\n\rHnByStringMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02hn\x18\x02 \x03(\t\"\n\n\x08\x45mptyMsg2\xfa\x01\n\x02Hn\x12*\n\nHelloWorld\x12\x0c.Hn.HelloMsg\x1a\x0c.Hn.HelloMsg\"\x00\x12#\n\x05GetHs\x12\r.Hn.VertexMsg\x1a\t.Hn.HsMsg\"\x00\x12#\n\x05\x41\x64\x64Hs\x12\t.Hn.HsMsg\x1a\r.Hn.VertexMsg\"\x00\x12&\n\x08\x44\x65leteHs\x12\t.Hn.HsMsg\x1a\r.Hn.VertexMsg\"\x00\x12\"\n\x05GetHn\x12\x0c.Hn.EmptyMsg\x1a\t.Hn.HsMsg\"\x00\x12\x32\n\x10\x43reateHnByString\x12\x11.Hn.HnByStringMsg\x1a\t.Hn.HnMsg\"\x00\x62\x06proto3'
)



_HSMSG_HSTYPE = _descriptor.EnumDescriptor(
  name='HsType',
  full_name='Hn.HsMsg.HsType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERTEX', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALPHA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BETA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=232,
  serialized_end=273,
)
_sym_db.RegisterEnumDescriptor(_HSMSG_HSTYPE)


_HELLOMSG = _descriptor.Descriptor(
  name='HelloMsg',
  full_name='Hn.HelloMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello', full_name='Hn.HelloMsg.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=51,
)


_VERTEXMSG = _descriptor.Descriptor(
  name='VertexMsg',
  full_name='Hn.VertexMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='Hn.VertexMsg.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=80,
)


_HSMSG = _descriptor.Descriptor(
  name='HsMsg',
  full_name='Hn.HsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='Hn.HsMsg.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simplex', full_name='Hn.HsMsg.simplex', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partOf', full_name='Hn.HsMsg.partOf', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hsType', full_name='Hn.HsMsg.hsType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='R', full_name='Hn.HsMsg.R', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t', full_name='Hn.HsMsg.t', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='M', full_name='Hn.HsMsg.M', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N', full_name='Hn.HsMsg.N', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='psi', full_name='Hn.HsMsg.psi', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HSMSG_HSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=273,
)


_DELETEHSMSG = _descriptor.Descriptor(
  name='DeleteHsMsg',
  full_name='Hn.DeleteHsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='Hn.DeleteHsMsg.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='R', full_name='Hn.DeleteHsMsg.R', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=315,
)


_HNMSG_HNENTRY = _descriptor.Descriptor(
  name='HnEntry',
  full_name='Hn.HnMsg.HnEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Hn.HnMsg.HnEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Hn.HnMsg.HnEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=423,
)

_HNMSG = _descriptor.Descriptor(
  name='HnMsg',
  full_name='Hn.HnMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Hn.HnMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Hn', full_name='Hn.HnMsg.Hn', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HNMSG_HNENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=423,
)


_HNBYSTRINGMSG = _descriptor.Descriptor(
  name='HnByStringMsg',
  full_name='Hn.HnByStringMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Hn.HnByStringMsg.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hn', full_name='Hn.HnByStringMsg.hn', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=466,
)


_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='Hn.EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=478,
)

_HSMSG.fields_by_name['hsType'].enum_type = _HSMSG_HSTYPE
_HSMSG_HSTYPE.containing_type = _HSMSG
_HNMSG_HNENTRY.fields_by_name['value'].message_type = _HSMSG
_HNMSG_HNENTRY.containing_type = _HNMSG
_HNMSG.fields_by_name['Hn'].message_type = _HNMSG_HNENTRY
DESCRIPTOR.message_types_by_name['HelloMsg'] = _HELLOMSG
DESCRIPTOR.message_types_by_name['VertexMsg'] = _VERTEXMSG
DESCRIPTOR.message_types_by_name['HsMsg'] = _HSMSG
DESCRIPTOR.message_types_by_name['DeleteHsMsg'] = _DELETEHSMSG
DESCRIPTOR.message_types_by_name['HnMsg'] = _HNMSG
DESCRIPTOR.message_types_by_name['HnByStringMsg'] = _HNBYSTRINGMSG
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloMsg = _reflection.GeneratedProtocolMessageType('HelloMsg', (_message.Message,), {
  'DESCRIPTOR' : _HELLOMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.HelloMsg)
  })
_sym_db.RegisterMessage(HelloMsg)

VertexMsg = _reflection.GeneratedProtocolMessageType('VertexMsg', (_message.Message,), {
  'DESCRIPTOR' : _VERTEXMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.VertexMsg)
  })
_sym_db.RegisterMessage(VertexMsg)

HsMsg = _reflection.GeneratedProtocolMessageType('HsMsg', (_message.Message,), {
  'DESCRIPTOR' : _HSMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.HsMsg)
  })
_sym_db.RegisterMessage(HsMsg)

DeleteHsMsg = _reflection.GeneratedProtocolMessageType('DeleteHsMsg', (_message.Message,), {
  'DESCRIPTOR' : _DELETEHSMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.DeleteHsMsg)
  })
_sym_db.RegisterMessage(DeleteHsMsg)

HnMsg = _reflection.GeneratedProtocolMessageType('HnMsg', (_message.Message,), {

  'HnEntry' : _reflection.GeneratedProtocolMessageType('HnEntry', (_message.Message,), {
    'DESCRIPTOR' : _HNMSG_HNENTRY,
    '__module__' : 'hypernetwork_pb2'
    # @@protoc_insertion_point(class_scope:Hn.HnMsg.HnEntry)
    })
  ,
  'DESCRIPTOR' : _HNMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.HnMsg)
  })
_sym_db.RegisterMessage(HnMsg)
_sym_db.RegisterMessage(HnMsg.HnEntry)

HnByStringMsg = _reflection.GeneratedProtocolMessageType('HnByStringMsg', (_message.Message,), {
  'DESCRIPTOR' : _HNBYSTRINGMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.HnByStringMsg)
  })
_sym_db.RegisterMessage(HnByStringMsg)

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:Hn.EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)


_HNMSG_HNENTRY._options = None

_HN = _descriptor.ServiceDescriptor(
  name='Hn',
  full_name='Hn.Hn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=481,
  serialized_end=731,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloWorld',
    full_name='Hn.Hn.HelloWorld',
    index=0,
    containing_service=None,
    input_type=_HELLOMSG,
    output_type=_HELLOMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetHs',
    full_name='Hn.Hn.GetHs',
    index=1,
    containing_service=None,
    input_type=_VERTEXMSG,
    output_type=_HSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddHs',
    full_name='Hn.Hn.AddHs',
    index=2,
    containing_service=None,
    input_type=_HSMSG,
    output_type=_VERTEXMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteHs',
    full_name='Hn.Hn.DeleteHs',
    index=3,
    containing_service=None,
    input_type=_HSMSG,
    output_type=_VERTEXMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetHn',
    full_name='Hn.Hn.GetHn',
    index=4,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_HSMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateHnByString',
    full_name='Hn.Hn.CreateHnByString',
    index=5,
    containing_service=None,
    input_type=_HNBYSTRINGMSG,
    output_type=_HNMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HN)

DESCRIPTOR.services_by_name['Hn'] = _HN

# @@protoc_insertion_point(module_scope)
