# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hypernetwork.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hypernetwork.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12hypernetwork.proto\"\x1f\n\rVertexMessage\x12\x0e\n\x06vertex\x18\x01 \x01(\t\"\xd5\x01\n\x13HypersimplexMessage\x12\x0e\n\x06vertex\x18\x01 \x01(\t\x12\x0f\n\x07simplex\x18\x02 \x03(\t\x12\x0e\n\x06partOf\x18\x03 \x03(\t\x12+\n\x06hsType\x18\x04 \x01(\x0e\x32\x1b.HypersimplexMessage.HsType\x12\t\n\x01R\x18\x05 \x01(\t\x12\t\n\x01t\x18\x06 \x01(\x05\x12\t\n\x01M\x18\x07 \x03(\t\x12\t\n\x01N\x18\x08 \x01(\t\x12\t\n\x01\x66\x18\t \x01(\t\")\n\x06HsType\x12\n\n\x06VERTEX\x10\x00\x12\t\n\x05\x41LPHA\x10\x01\x12\x08\n\x04\x42\x45TA\x10\x02\",\n\x0f\x44\x65leteHsMessage\x12\x0e\n\x06vertex\x18\x01 \x01(\t\x12\t\n\x01R\x18\x02 \x01(\t\"\xac\x01\n\x13HypernetworkMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x0chypernetwork\x18\x02 \x03(\x0b\x32&.HypernetworkMessage.HypernetworkEntry\x1aI\n\x11HypernetworkEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.HypersimplexMessage:\x02\x38\x01\"\x0e\n\x0c\x45mptyMessage2\xe6\x01\n\x02HT\x12\x37\n\x0fGetHypersimplex\x12\x0e.VertexMessage\x1a\x14.HypersimplexMessage\x12\x37\n\x0f\x41\x64\x64Hypersimplex\x12\x14.HypersimplexMessage\x1a\x0e.VertexMessage\x12:\n\x12\x44\x65leteHypersimplex\x12\x14.HypersimplexMessage\x1a\x0e.VertexMessage\x12\x32\n\x0fGetHypernetwork\x12\x10.DeleteHsMessage\x1a\r.EmptyMessageb\x06proto3')
)



_HYPERSIMPLEXMESSAGE_HSTYPE = _descriptor.EnumDescriptor(
  name='HsType',
  full_name='HypersimplexMessage.HsType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VERTEX', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALPHA', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BETA', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=228,
  serialized_end=269,
)
_sym_db.RegisterEnumDescriptor(_HYPERSIMPLEXMESSAGE_HSTYPE)


_VERTEXMESSAGE = _descriptor.Descriptor(
  name='VertexMessage',
  full_name='VertexMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='VertexMessage.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=53,
)


_HYPERSIMPLEXMESSAGE = _descriptor.Descriptor(
  name='HypersimplexMessage',
  full_name='HypersimplexMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='HypersimplexMessage.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simplex', full_name='HypersimplexMessage.simplex', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partOf', full_name='HypersimplexMessage.partOf', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hsType', full_name='HypersimplexMessage.hsType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='R', full_name='HypersimplexMessage.R', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='HypersimplexMessage.t', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='M', full_name='HypersimplexMessage.M', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='N', full_name='HypersimplexMessage.N', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='HypersimplexMessage.f', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HYPERSIMPLEXMESSAGE_HSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=269,
)


_DELETEHSMESSAGE = _descriptor.Descriptor(
  name='DeleteHsMessage',
  full_name='DeleteHsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertex', full_name='DeleteHsMessage.vertex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='R', full_name='DeleteHsMessage.R', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=315,
)


_HYPERNETWORKMESSAGE_HYPERNETWORKENTRY = _descriptor.Descriptor(
  name='HypernetworkEntry',
  full_name='HypernetworkMessage.HypernetworkEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='HypernetworkMessage.HypernetworkEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='HypernetworkMessage.HypernetworkEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=490,
)

_HYPERNETWORKMESSAGE = _descriptor.Descriptor(
  name='HypernetworkMessage',
  full_name='HypernetworkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HypernetworkMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hypernetwork', full_name='HypernetworkMessage.hypernetwork', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HYPERNETWORKMESSAGE_HYPERNETWORKENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=490,
)


_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=506,
)

_HYPERSIMPLEXMESSAGE.fields_by_name['hsType'].enum_type = _HYPERSIMPLEXMESSAGE_HSTYPE
_HYPERSIMPLEXMESSAGE_HSTYPE.containing_type = _HYPERSIMPLEXMESSAGE
_HYPERNETWORKMESSAGE_HYPERNETWORKENTRY.fields_by_name['value'].message_type = _HYPERSIMPLEXMESSAGE
_HYPERNETWORKMESSAGE_HYPERNETWORKENTRY.containing_type = _HYPERNETWORKMESSAGE
_HYPERNETWORKMESSAGE.fields_by_name['hypernetwork'].message_type = _HYPERNETWORKMESSAGE_HYPERNETWORKENTRY
DESCRIPTOR.message_types_by_name['VertexMessage'] = _VERTEXMESSAGE
DESCRIPTOR.message_types_by_name['HypersimplexMessage'] = _HYPERSIMPLEXMESSAGE
DESCRIPTOR.message_types_by_name['DeleteHsMessage'] = _DELETEHSMESSAGE
DESCRIPTOR.message_types_by_name['HypernetworkMessage'] = _HYPERNETWORKMESSAGE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VertexMessage = _reflection.GeneratedProtocolMessageType('VertexMessage', (_message.Message,), {
  'DESCRIPTOR' : _VERTEXMESSAGE,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:VertexMessage)
  })
_sym_db.RegisterMessage(VertexMessage)

HypersimplexMessage = _reflection.GeneratedProtocolMessageType('HypersimplexMessage', (_message.Message,), {
  'DESCRIPTOR' : _HYPERSIMPLEXMESSAGE,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:HypersimplexMessage)
  })
_sym_db.RegisterMessage(HypersimplexMessage)

DeleteHsMessage = _reflection.GeneratedProtocolMessageType('DeleteHsMessage', (_message.Message,), {
  'DESCRIPTOR' : _DELETEHSMESSAGE,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:DeleteHsMessage)
  })
_sym_db.RegisterMessage(DeleteHsMessage)

HypernetworkMessage = _reflection.GeneratedProtocolMessageType('HypernetworkMessage', (_message.Message,), {

  'HypernetworkEntry' : _reflection.GeneratedProtocolMessageType('HypernetworkEntry', (_message.Message,), {
    'DESCRIPTOR' : _HYPERNETWORKMESSAGE_HYPERNETWORKENTRY,
    '__module__' : 'hypernetwork_pb2'
    # @@protoc_insertion_point(class_scope:HypernetworkMessage.HypernetworkEntry)
    })
  ,
  'DESCRIPTOR' : _HYPERNETWORKMESSAGE,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:HypernetworkMessage)
  })
_sym_db.RegisterMessage(HypernetworkMessage)
_sym_db.RegisterMessage(HypernetworkMessage.HypernetworkEntry)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'hypernetwork_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)


_HYPERNETWORKMESSAGE_HYPERNETWORKENTRY._options = None

_HT = _descriptor.ServiceDescriptor(
  name='HT',
  full_name='HT',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=509,
  serialized_end=739,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetHypersimplex',
    full_name='HT.GetHypersimplex',
    index=0,
    containing_service=None,
    input_type=_VERTEXMESSAGE,
    output_type=_HYPERSIMPLEXMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddHypersimplex',
    full_name='HT.AddHypersimplex',
    index=1,
    containing_service=None,
    input_type=_HYPERSIMPLEXMESSAGE,
    output_type=_VERTEXMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteHypersimplex',
    full_name='HT.DeleteHypersimplex',
    index=2,
    containing_service=None,
    input_type=_HYPERSIMPLEXMESSAGE,
    output_type=_VERTEXMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetHypernetwork',
    full_name='HT.GetHypernetwork',
    index=3,
    containing_service=None,
    input_type=_DELETEHSMESSAGE,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HT)

DESCRIPTOR.services_by_name['HT'] = _HT

# @@protoc_insertion_point(module_scope)
